
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'k|\xa4\xa0$\xbc\x95\xfa\xb6\xa5|\xa5\x1a~\x1bn'
    
_lr_action_items = {'RPAREN':([2,4,6,7,12,15,16,17,18,19,20,],[-5,-9,-8,-10,18,-7,-6,-2,-11,-3,-4,]),'DIVIDE':([2,4,6,7,15,16,18,19,20,],[9,-9,-8,-10,-7,-6,-11,9,9,]),'DELIM':([0,2,3,4,5,6,7,11,15,16,17,18,19,20,],[3,-5,3,-9,3,-8,-10,17,-7,-6,-2,-11,-3,-4,]),'NUMBER':([0,3,5,9,10,13,14,],[4,4,4,4,4,4,4,]),'TIMES':([2,4,6,7,15,16,18,19,20,],[10,-9,-8,-10,-7,-6,-11,10,10,]),'PLUS':([2,4,6,7,8,11,12,15,16,17,18,19,20,],[-5,-9,-8,-10,13,13,13,-7,-6,-2,-11,-3,-4,]),'LPAREN':([0,3,5,9,10,13,14,],[5,5,5,5,5,5,5,]),'VARIABLE':([0,3,5,9,10,13,14,],[7,7,7,7,7,7,7,]),'MINUS':([2,4,6,7,8,11,12,15,16,17,18,19,20,],[-5,-9,-8,-10,14,14,14,-7,-6,-2,-11,-3,-4,]),'$end':([1,2,4,6,7,8,15,16,17,18,19,20,],[0,-5,-9,-8,-10,-1,-7,-6,-2,-11,-3,-4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'latex':([0,],[1,]),'term':([0,3,5,13,14,],[2,2,2,19,20,]),'expression':([0,3,5,],[8,11,12,]),'factor':([0,3,5,9,10,13,14,],[6,6,6,15,16,6,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> latex","S'",1,None,None,None),
  ('latex -> expression','latex',1,'p_latex','yacc.py',8),
  ('expression -> DELIM expression DELIM','expression',3,'p_expression','yacc.py',12),
  ('expression -> expression PLUS term','expression',3,'p_expression','yacc.py',13),
  ('expression -> expression MINUS term','expression',3,'p_expression','yacc.py',14),
  ('expression -> term','expression',1,'p_expression','yacc.py',15),
  ('term -> term TIMES factor','term',3,'p_term','yacc.py',25),
  ('term -> term DIVIDE factor','term',3,'p_term','yacc.py',26),
  ('term -> factor','term',1,'p_term','yacc.py',27),
  ('factor -> NUMBER','factor',1,'p_factor','yacc.py',37),
  ('factor -> VARIABLE','factor',1,'p_factor','yacc.py',38),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor','yacc.py',39),
]
