
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '"\xe0\'\xa1\xbd\x8b\xbe%\xfc\x03\x7f\xc5\xdfm\x9e\x9b'
    
_lr_action_items = {'RPAREN':([1,6,12,],[-8,12,-7,]),'DIVIDE':([1,5,12,],[-8,7,-7,]),'POWER':([1,5,12,],[-8,8,-7,]),'NUMBER':([0,3,7,8,9,10,11,],[1,1,1,1,1,1,1,]),'TIMES':([1,5,12,],[-8,9,-7,]),'PLUS':([1,5,12,],[-8,10,-7,]),'LPAREN':([0,3,7,8,9,10,11,],[3,3,3,3,3,3,3,]),'LINE':([0,],[4,]),'MINUS':([1,5,12,],[-8,11,-7,]),'$end':([1,2,4,12,13,14,15,16,17,],[-8,0,-1,-7,-5,-6,-4,-2,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,7,8,9,10,11,],[5,6,13,14,15,16,17,]),'statement':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> LINE','statement',1,'p_statement_expr','yacc.py',8),
  ('statement -> expression PLUS expression','statement',3,'p_expression_binop','yacc.py',12),
  ('statement -> expression MINUS expression','statement',3,'p_expression_binop','yacc.py',13),
  ('statement -> expression TIMES expression','statement',3,'p_expression_binop','yacc.py',14),
  ('statement -> expression DIVIDE expression','statement',3,'p_expression_binop','yacc.py',15),
  ('statement -> expression POWER expression','statement',3,'p_expression_binop','yacc.py',16),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','yacc.py',24),
  ('expression -> NUMBER','expression',1,'p_expression','yacc.py',25),
]
